- name: "Upgrade system dependencies"
  hosts: "{{ target_hosts }}"
  become: yes
  tasks:
    - name: "Upgrade dependencies"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
      apt:
        update_cache: true
        upgrade: "yes"

